version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-stagiaires
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_stagiaires
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8762:8762"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server

  stagiaire-service:
    build: ./stagiaire-service
    container_name: stagiaire-service
    ports:
      - "9091:9091"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gestion_stagiaires

  encadreur-service:
    build: ./encadreur-service
    container_name: encadreur-service
    ports:
      - "9092:9092"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gestion_stagiaires

volumes:
  mysql_data:
